// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zkqagadywxhnejloabtt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InprcWFnYWR5d3hobmVqbG9hYnR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1MDQ1MDAsImV4cCI6MjA2MTA4MDUwMH0.75TzNgKKp7KP7RUALeB_6jCWrJ7fIyOpOx9RsjL3fFM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);